# Generated by Django 2.0.4 on 2018-06-05 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0013_auto_20180531_2038'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Genre',
        ),
        migrations.AddField(
            model_name='comment',
            name='message_html',
            field=models.TextField(blank=True, default='', editable=False),
        ),
    ]
